//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiaoZi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advice
    {
        public int AdviceID { get; set; }
        public string Advice_Content { get; set; }
        public Nullable<System.DateTime> Advice_Time { get; set; }
        public Nullable<bool> AdviceFlag { get; set; }
    }
}
