//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiaoZi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remark_User_Comments_Reply
    {
        public string Title { get; set; }
        public System.DateTime Remark_time { get; set; }
        public int RemarkID { get; set; }
        public string UserName { get; set; }
        public int UserID { get; set; }
        public Nullable<int> pinglunshu { get; set; }
    }
}
