//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiaoZi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShuoshuoComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShuoshuoComment()
        {
            this.ShuoshuoComment_Reply = new HashSet<ShuoshuoComment_Reply>();
            this.ShuoshuoComment_Reply1 = new HashSet<ShuoshuoComment_Reply>();
        }
    
        public int ShuoshuoCommentID { get; set; }
        public Nullable<System.DateTime> Comment_Time { get; set; }
        public string Comment_Content { get; set; }
        public int UserID { get; set; }
        public int ShuoshuoID { get; set; }
    
        public virtual Shuoshuo Shuoshuo { get; set; }
        public virtual Shuoshuo Shuoshuo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShuoshuoComment_Reply> ShuoshuoComment_Reply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShuoshuoComment_Reply> ShuoshuoComment_Reply1 { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
